=== willdjames/xml-utills/src/venda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >
	<xsd:element name="venda">		
        <xsd:complexType>
			<xsd:sequence>
				<xsd:element name="formaPagamento" type="xsd:string" />
			    <xsd:element name="produtos">
			    	<xsd:complexType>
			    		<xsd:sequence>
			    			<xsd:element name="produto" maxOccurs="unbounded">
			    				<xsd:complexType>
			    					<xsd:sequence>
			    						<xsd:element name="nome" type="xsd:string"/>
			    						<xsd:element name="valor" type="xsd:double"/>		
			    					</xsd:sequence>
			    				</xsd:complexType>
			    			</xsd:element>
			    		</xsd:sequence>
			    	</xsd:complexType>
			    </xsd:element>
			</xsd:sequence>
			<xsd:attribute name="moeda" type="xsd:string" />
		</xsd:complexType>
    </xsd:element>
</xsd:schema>

=== willdjames/xml-utills/src/venda.xml
<?xml version="1.0" encoding="UTF-8"?>
<venda moeda="real" xsi:noNamespaceSchemaLocation="venda.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<formaPagamento>Credito</formaPagamento>
	<produtos>
		<produto>
			<nome>Livro 01</nome>
			<valor>19.90</valor>
		</produto>
		<produto>
			<nome>Livro 02</nome>
			<valor>19.90</valor>
		</produto>
	</produtos>
</venda>
